services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    volumes:
      - ./documents:/app/documents
    environment:
      - FLASK_ENV=production
    depends_on:
      - prometheus
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
